language: python
python:
  - 2.7
env:
  #### Out of tree builds (default):
  # Debug build:
  - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_CSYMPY_RCP="yes"
  # Debug build with CSYMPY_ASSERT on
 before_install:
  - sudo apt-get update
  - sudo apt-get install cmake libgmp-dev
  - if [[ "${WITH_BFD}" == "yes" ]]; then
        sudo apt-get install binutils-dev;
    fi
  - if [[ "${WITH_ECM}" == "yes" ]]; then
        sudo apt-get install libecm-dev;
    fi
install:
  - if [[ "${WITH_PYTHON}" == "yes" ]]; then
        pip install cython sympy --use-mirrors;
    fi
before_script:
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DWITH_BFD=${WITH_BFD} -DWITH_PYTHON=${WITH_PYTHON} -DWITH_CSYMPY_ASSERT=${WITH_CSYMPY_ASSERT} -DWITH_CSYMPY_RCP=${WITH_CSYMPY_RCP} -DWITH_ECM=${WITH_ECM} ${SOURCE_DIR}
  - make
script:
  - if [[ "${TEST_IN_TREE}" == "yes" ]]; then
        export SOURCE_DIR=.;
    else
        mkdir build;
        cd build;
        export SOURCE_DIR=..;
    fi
  - $SOURCE_DIR/bin/test_travis.sh
notifications:
  email: false
